cobranca:
  valor:
    adicional:
      consulta: 10
      cirurgia: 1000
  dias:
    vencimento: 10

inserir:
  contrato:
    startup: true
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/planos
    username: multiskill-user
    password: postgres
  h2:
    console:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/planos